use serde::{Serialize, Deserialize};
///
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SetupAttemptPaymentMethodDetailsSofort {
    ///Bank code of bank associated with the bank account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank_code: Option<String>,
    ///Name of the bank associated with the bank account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    ///Bank Identifier Code of the bank associated with the bank account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    ///The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit: Option<serde_json::Value>,
    ///The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit_mandate: Option<serde_json::Value>,
    ///Last four characters of the IBAN.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub iban_last4: Option<String>,
    /**Preferred language of the Sofort authorization page that the customer is redirected to.
Can be one of `en`, `de`, `fr`, or `nl`*/
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preferred_language: Option<String>,
    /**Owner's verified full name. Values are verified or provided by Sofort directly
(if supported) at the time of authorization or settlement. They cannot be set or mutated.*/
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_name: Option<String>,
}
impl std::fmt::Display for SetupAttemptPaymentMethodDetailsSofort {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        write!(f, "{}", serde_json::to_string(self).unwrap())
    }
}