use serde::{Serialize, Deserialize};
///
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SetupAttemptPaymentMethodDetailsIdeal {
    ///The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `handelsbanken`, `ing`, `knab`, `moneyou`, `n26`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank: Option<String>,
    ///The Bank Identifier Code of the customer's bank.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    ///The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit: Option<serde_json::Value>,
    ///The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit_mandate: Option<serde_json::Value>,
    ///Last four characters of the IBAN.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub iban_last4: Option<String>,
    /**Owner's verified full name. Values are verified or provided by iDEAL directly
(if supported) at the time of authorization or settlement. They cannot be set or mutated.*/
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_name: Option<String>,
}
impl std::fmt::Display for SetupAttemptPaymentMethodDetailsIdeal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        write!(f, "{}", serde_json::to_string(self).unwrap())
    }
}